version: 2
updates:
  # Docker image dependencies
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "cron"
      cronjob: "15 1 * * *"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "cron"
      cronjob: "15 1 * * *"

  # Java (Maven)
  - package-ecosystem: "gradle"
    directory: "/src/calc-service"
    open-pull-requests-limit: 25
    schedule:
      interval: "cron"
      cronjob: "15 1 * * *"

  # Go
  - package-ecosystem: "gomod"
    directory: "/src/entropy-service"
    open-pull-requests-limit: 25
    schedule:
      interval: "cron"
      cronjob: "15 1 * * *"
