name: Build & Test (Java)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/calc-service/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/calc-service/**"

jobs:
  build:
    name: Build & Test calc-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/calc-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: |
          ./gradlew clean build --no-daemon
