name: Build & Test (Go)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/entropy-service/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/entropy-service/**"

jobs:
  build:
    name: Build & Test entropy-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/entropy-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Lint (optional)
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
